---
title: "R Notebook"
output: html_notebook
---

```{r}
library(XML)
books <-  "https://www.w3schools.com/xml/books.xml"
library(plyr)
ldply(xmlToList(books), function(x) { data.frame(x[!names(x)=="author"]) } )
```

```{r list-all-xml-files}
all_files_xml <- list.files("./witsml", recursive = TRUE, full.names = TRUE, 
                        include.dirs = TRUE, pattern = "*.xml")

# get the file for trajectory
traj_files <- grep(pattern = "trajectory", ignore.case = TRUE, 
                   value = TRUE, x = all_files_xml)
url <- traj_files[3]
```


```{r}
ldply(xmlToList(traj_files[3]), function(x) {
    data.frame(x[names(x) == "trajectoryStation"]) } )
```

```{r}
x <- xmlToList(traj_files[3])
names(x)
```

```{r}
str(x[1], max.level = 2)
```

```{r}
lapply(x[1], "[", "trajectoryStation")
# do.call(rbind.data.frame, lapply(x[1], "[", "trajectoryStation"))
```

```{r}
lapply(x$trajectory[17], "[", c("md", "tvd"))
# do.call(rbind.data.frame, lapply(x$trajectory[17]["md"], "[", c("text")))
```

```{r}
# unlist(x$trajectory[17])

lapply(x$trajectory$trajectoryStation, function(x) unlist(x))
```


```{r}
names(x$trajectory)
```

```{r}
names(x$trajectory$commonData)
```

```{r}
sapply(x$trajectory, names)
```




```{r}
df <- xmlToDataFrame(traj_files[3])
df
```

